http.Fetch( "http://s3.amazonaws.com/USBucketMapimg/mapicons/manifest.lua", function( body, len, headers, code ) 
	MAPVOTE.IconCounts = CompileString( body, "KMVMapManifest" )( )
	KLogf( 4, "[KMV] Loaded map manifest, %i maps", table.Count( MAPVOTE.IconCounts ) )
end, function( err )
	KLogf( 2, "[ERROR] Loading map manifest failed! %s", err )
end )